AllCops:
  Include:
  - "**/*.gemspec"
  - "**/Gemfile"
  Exclude:
  - "vendor/**/*"
  - "spec/**/*"
  - "features/**/*"
  - "db/schema.rb"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
